// import ApiService from '@/services/ApiService.js'

const data = [
  {
    id: '8b0e7aec-aacc-425c-a297-605af4531bc3',
    pmsId: 217460,
    status: 'CHANGED',
    roomType: 'DKI',
    arrivalDate: '2020-06-21',
    departureDate: '2020-06-22',
    guestProfile: {
      id: '7751ff35-173c-4ce4-87d3-57ffda560c44',
      pmsId: 217460,
      person: {
        nameTitle: 'MS',
        firstName: 'JOHN',
        middleName: '',
        lastName: 'SMITH',
        dateOfBirth: '',
        countryOfBirth: '',
        gender: '',
        nationality: '',
        email: '',
      },
      address: {
        type: 'AddressNONE',
        address: [],
      },
      document: {
        type: 'DocumentNONE',
        document: [],
      },
    },
    shares: null,
  },
  {
    id: 'd5c3f690-7078-406a-b036-4ff119f47e69',
    pmsId: 54710,
    status: 'RESERVED',
    roomType: 'DKI',
    arrivalDate: '2020-06-21',
    departureDate: '2020-06-22',
    guestProfile: {
      id: 'f828364e-fd9f-423b-a3c0-0cd31e97874e',
      pmsId: 54710,
      person: {
        nameTitle: 'Mr',
        firstName: 'Sam',
        middleName: '',
        lastName: 'Riad',
        dateOfBirth: '',
        countryOfBirth: '',
        gender: '',
        nationality: '',
        email: '',
      },
      address: {
        type: 'AddressNONE',
        address: [],
      },
      document: {
        type: 'DocumentNONE',
        document: [],
      },
    },
    shares: null,
  },
  {
    id: 'e2567155-52b4-46c1-84f2-cc30abc5b8a8',
    pmsId: 218210,
    status: 'CHANGED',
    roomType: 'DKI',
    arrivalDate: '2020-06-22',
    departureDate: '2020-06-23',
    guestProfile: {
      id: '6045bcb0-5d05-414f-8298-fcf289930640',
      pmsId: 218210,
      person: {
        nameTitle: 'MRS',
        firstName: 'SARA',
        middleName: '',
        lastName: 'SMITH',
        dateOfBirth: '',
        countryOfBirth: '',
        gender: '',
        nationality: '',
        email: '',
      },
      address: {
        type: 'AddressNONE',
        address: [],
      },
      document: {
        type: 'DocumentNONE',
        document: [],
      },
    },
    shares: null,
  },
  {
    id: '467bff90-9a09-4c5b-8ff6-66cd6897cb14',
    pmsId: 217710,
    status: 'CHANGED',
    roomType: 'DKI',
    arrivalDate: '2020-06-22',
    departureDate: '2020-06-23',
    guestProfile: {
      id: '6edceae8-4b50-48b6-8e27-d10efb88b9db',
      pmsId: 217710,
      person: {
        nameTitle: '',
        firstName: 'SAM',
        middleName: '',
        lastName: 'SERIOUS',
        dateOfBirth: '',
        countryOfBirth: '',
        gender: '',
        nationality: '',
        email: '',
      },
      address: {
        type: 'AddressNONE',
        address: [],
      },
      document: {
        type: 'DocumentNONE',
        document: [],
      },
    },
    shares: null,
  },
  {
    id: '78dfb59a-1837-4437-b838-8e137e9a58ba',
    pmsId: 217960,
    status: 'RESERVED',
    roomType: 'DKI',
    arrivalDate: '2020-06-22',
    departureDate: '2020-06-23',
    guestProfile: {
      id: 'add4003d-5f31-4dac-b581-c34e691a115f',
      pmsId: 217960,
      person: {
        nameTitle: '',
        firstName: '',
        middleName: '',
        lastName: 'SERIOUS',
        dateOfBirth: '',
        countryOfBirth: '',
        gender: '',
        nationality: '',
        email: '',
      },
      address: {
        type: 'AddressNONE',
        address: [],
      },
      document: {
        type: 'DocumentNONE',
        document: [],
      },
    },
    shares: null,
  },
  {
    id: 'c66d69dc-0676-4062-b2e5-79ae2269b770',
    pmsId: 218460,
    status: 'CANCELED',
    roomType: 'DKI',
    arrivalDate: '2020-06-22',
    departureDate: '2020-06-23',
    guestProfile: {
      id: '33d56bc8-537d-4c6a-ab2b-e9b584333078',
      pmsId: 218460,
      person: {
        nameTitle: 'MRS',
        firstName: 'SARA',
        middleName: '',
        lastName: 'SMITH',
        dateOfBirth: '',
        countryOfBirth: '',
        gender: '',
        nationality: '',
        email: '',
      },
      address: {
        type: 'AddressNONE',
        address: [],
      },
      document: {
        type: 'DocumentNONE',
        document: [],
      },
    },
    shares: null,
  },
  {
    id: 'c6660e4b-9b18-41ee-a182-03173bd46ef5',
    pmsId: 219460,
    status: 'CANCELED',
    roomType: 'DKI',
    arrivalDate: '2020-07-12',
    departureDate: '2020-07-20',
    guestProfile: {
      id: 'e70f5a6d-401e-474a-a6f0-513b825d78b4',
      pmsId: 219460,
      person: {
        nameTitle: 'MR',
        firstName: 'FRITZ',
        middleName: '',
        lastName: 'KOEHLER',
        dateOfBirth: '',
        countryOfBirth: '',
        gender: '',
        nationality: '',
        email: '',
      },
      address: {
        type: 'AddressNONE',
        address: [],
      },
      document: {
        type: 'DocumentNONE',
        document: [],
      },
    },
    shares: null,
  },
  {
    id: '32495af3-669a-4910-98d2-fab1f5bc13cf',
    pmsId: 219210,
    status: 'CANCELED',
    roomType: 'DKI',
    arrivalDate: '2020-07-12',
    departureDate: '2020-07-20',
    guestProfile: {
      id: 'c6002d2d-98a0-4325-aa77-8b6a7807b362',
      pmsId: 219210,
      person: {
        nameTitle: 'MR',
        firstName: 'FRITZ',
        middleName: '',
        lastName: 'KOEHLER',
        dateOfBirth: '',
        countryOfBirth: '',
        gender: '',
        nationality: '',
        email: '',
      },
      address: {
        type: 'AddressNONE',
        address: [],
      },
      document: {
        type: 'DocumentNONE',
        document: [],
      },
    },
    shares: null,
  },
  {
    id: '6e7ed162-a635-4c35-a601-1e9e97bda627',
    pmsId: 219710,
    status: 'CHANGED',
    roomType: 'DKI',
    arrivalDate: '2020-07-12',
    departureDate: '2020-07-20',
    guestProfile: {
      id: '08b08d0a-3b94-4629-afa7-6376f3f73b31',
      pmsId: 219710,
      person: {
        nameTitle: 'MRS',
        firstName: 'ANNA',
        middleName: 'MARIA',
        lastName: 'KOEHLER',
        dateOfBirth: '1901-07-12',
        countryOfBirth: 'AT',
        gender: 'F',
        nationality: 'DE',
        email: 'anna_maria@koehler.com',
      },
      address: {
        type: 'AddressNONE',
        address: [],
      },
      document: {
        type: 'DocumentNONE',
        document: [],
      },
    },
    shares: null,
  },
  {
    id: '41b42e12-6b47-4947-8a3e-d72696710dbe',
    pmsId: 218710,
    status: 'CANCELED',
    roomType: 'DKI',
    arrivalDate: '2020-07-12',
    departureDate: '2020-07-20',
    guestProfile: {
      id: 'dcd73308-cbba-4d70-a5a6-d1b6a5a58e4a',
      pmsId: 218710,
      person: {
        nameTitle: 'MR',
        firstName: 'FRITZ',
        middleName: '',
        lastName: 'KOEHLER',
        dateOfBirth: '',
        countryOfBirth: '',
        gender: '',
        nationality: '',
        email: '',
      },
      address: {
        type: 'AddressNONE',
        address: [],
      },
      document: {
        type: 'DocumentNONE',
        document: [],
      },
    },
    shares: null,
  },
  {
    id: 'fa81f3e1-2dc7-4f45-9b3b-c4e53ad5bb1f',
    pmsId: 218960,
    status: 'CANCELED',
    roomType: 'DKI',
    arrivalDate: '2020-07-12',
    departureDate: '2020-07-20',
    guestProfile: {
      id: '2e9f86c6-f2ef-4103-b468-37c9dd6bcd5e',
      pmsId: 218960,
      person: {
        nameTitle: 'MR',
        firstName: 'FRITZ',
        middleName: '',
        lastName: 'KOEHLER',
        dateOfBirth: '',
        countryOfBirth: '',
        gender: '',
        nationality: '',
        email: '',
      },
      address: {
        type: 'AddressNONE',
        address: [],
      },
      document: {
        type: 'DocumentNONE',
        document: [],
      },
    },
    shares: null,
  },
]

export const state = () => ({
  reservations: [],
})
export const mutations = {
  SET_RESERVATIONS(state, reservations) {
    state.reservations = reservations
  },
}
export const actions = {
  fetchReservations({ commit }) {
    commit('SET_RESERVATIONS', data)
    // return ApiService.getData().then((response) => {
    // })
  },
}
